Worksheet 0
Ayush Yonghang - 2358879

1. Python Version check

In [ ]:
import sys
print(sys.version)

3.11.11 (main, Dec  4 2024, 08:55:07) [GCC 11.4.0]


2. Data Types in Python
"Mutable Data Types: List Mutable objcets can be changed after they are created. Can be modified or changing their values without creating a new object.
Immutable Data Types: Tuple cannot be changed once they are created. Any operation that seems to modify an immutable object will actually create a new object instead of changing the original."

In [ ]:
# Mutable Data Types - list
myList = [12,13,14]
print("Original List: ", myList)

# Modifying the list (changing content)
myList.append(15)
print("Modified List: ", myList)

# Immutable Data Type - Tuple
myTuple = (1,2,3)
print("Original Tuple: ", myTuple)

myTuple.append(4)
print("Modified Tuple: ", myTuple)

Original List:  [12, 13, 14]
Modified List:  [12, 13, 14, 15]
Original Tuple:  (1, 2, 3)


AttributeError: 'tuple' object has no attribute 'append'

2.1 Some Common Data Types in Python

2.1.1 Numeric

In [ ]:
age = 54 #int
p = 3.14 #float
temp = -5.5 #float

print("Data types of variable age = ", type(age))
print("Data types of variable p = ", type(p))
print("Data types of variable temp = ", type(temp))

Data types of variable age =  <class 'int'>
Data types of variable p =  <class 'float'>
Data types of variable temp =  <class 'float'>


2.1.2 Sequence

In [ ]:
#These data types are ordered collection of items. You can access elements by their position (index)
#str- represent sequence of characters enclosed by double or single quotes.
#it is an immutable sequence

name = "Rameshwor"
action = "Namaste"
address = "Kathmandu"

print("Data type of the variable name = ", type(name))
print("Data type of the variable action = ", type(action))
print("Data type of the variable address = ", type(address))

#slicing only one element
print("The first letter of the name is: ", name[0])
print("The last letter of the name is: ", name[-1])

#Slicing a range of elements
print("The second letter to the fourth of the name is: ", name[1:4])
print("The first two letters of the name are: ", name[:2])
print("Substring starting from the third letter is: ", name[2:])


Data type of the variable name =  <class 'str'>
Data type of the variable action =  <class 'str'>
Data type of the variable address =  <class 'str'>
The first letter of the name is:  R
The last letter of the name is:  r
The second letter to the fourth of the name is:  ame
The first two letters of the name are:  Ra
Substring starting from the third letter is:  meshwor


2.1.3 List

In [ ]:
""" Represent lists, which can contain mixed data types and are mutable """
list = [10,20,30,40]
mixedList = [9, "Ayush", True]
mixedList[0] = False
mixedList

[False, 'Ayush', True]

2.1.4 Tuple

In [ ]:
""" Represnt tuples which are ordered and immutable collections """

colors = ("white", "red", "orange", "green")
print("First element: ", colors[0])
print("Last two elements: ", colors[2:])
print("Middle two elements: ", colors[1:3])
colors[0] = "yellow"
colors

First element:  white
Last two elements:  ('orange', 'green')
Middle two elements:  ('red', 'orange')


TypeError: 'tuple' object does not support item assignment

2.1.5 Mapping

In [ ]:
#This data types store key-value pairs
"""dict - represent dictionaries, which can store various data types
as value associated with unique key"""

person = {'name': 'Ayush Yonghang', 'age': 23, 'address': 'Nakhipot'}
print(f"Hello my name is {person['name']}. I am {person['age']} years old and I live at {person['address']}.")
print("All keys: ", list(person.keys()))
print("All values: ", list(person.values()))

Hello my name is Ayush Yonghang. I am 23 years old and I live at Nakhipot.


TypeError: 'list' object is not callable

2.1.6 Set

In [ ]:
# Set are unordered  collection of unique element.
# Useful for membership testing and eliminating duplicate entries

# set - mutable collection of unique items : (1,2,3)
# frozenset - immutable version of set : frozen([1,2,3])

unique_numbers = {1,4,2,2,3,4,5,5}
print(unique_numbers)

{1, 2, 3, 4, 5}


2.1.7 Boolean

In [ ]:
# contains types that represent truth values
# bool: Represents boolean values (True or False).

is_student = True
has_license = False
print("Data types of the variable is_student = ", type(is_student))
print("Data types of the variable has_license = ", type(has_license))


Data types of the variable is_student =  <class 'bool'>
Data types of the variable has_license =  <class 'bool'>


2.1.8 Special

In [ ]:
# Category is used for unique data types that do not fit into the other categories

# NoneType: Represents the absence of a value or a null value (e.g., None).

result = None

3. Logical Statement and Loops

"""
Python code can be decomposed into packages, modules, statements, and expressions, as follows:

1. Expressions create and process objects:
• Expressions are part of statements that return a value, such as variables, operators, or function calls.
2. Statements contain expressions:
• Statements are sections of code that perform an action. The main groups of Python state- ments are: assignment statements, print statements, conditional statements (if, break, con- tinue, try), and looping statements (for, while).
3. Module Contain statements:
• Modules are Python files that contain Python statements, and are also called scripts.
4. Packages are composed of modules:
• Packages are Python programs that collect related modules together within a single directory hierarchy.
"""

3.1 Logical Statement

In [ ]:
n = 5
if n > 0:
  print("Positive")
elif n ==0:
  print("zero")
else:
  print("Negative")

Positive


In [ ]:
x = 20
y = 40
if x>0 and y<20:
  print("Both conditions are true")
if x>0 or y>20:
  print("Atleast one condition is true")
if not x==0:
  print("x is not equal to 0")

Atleast one condition is true
x is not equal to 0


In [ ]:
#define two boolean variables
a = True
b = False
#using the "and" operator
if a and b:
  print("Both a and b are true.")
else:
  print("Either a or b is false.")
#using the "or" operator
if a or b:
  print("At least one of a or b is true.")
else:
  print("Both a and b are false.")
#using the "not" operator
if not a:
  print("a is false.")
else:
  print("a is true")

Either a or b is false.
At least one of a or b is true.
a is true


3.2 Loops

In [ ]:
""" for loop: Iterates over a sequence (like a list, tuple, or string).
         for item in iterable:
         - Code to execute for each item

• while loop: Repeats as long as a condition is true.
         while condition:
             - Code to execute while condition is true

• break: Exits the loop immediately.
         for item in iterable:
             if some_condition:
             break
             - Exit loop

• continue: Skips the current iteration and continues with the next iteration of the loop.
         for item in iterable:
             if some_condition:
                 continue
                  - Skip to the next iteration
                  """

' for loop: Iterates over a sequence (like a list, tuple, or string).\n         for item in iterable:\n         - Code to execute for each item\n         \n• while loop: Repeats as long as a condition is true.\n         while condition:\n             - Code to execute while condition is true\n             \n• break: Exits the loop immediately.\n         for item in iterable:\n             if some_condition:\n             break \n             - Exit loop\n\n• continue: Skips the current iteration and continues with the next iteration of the loop.\n         for item in iterable:\n             if some_condition:\n                 continue  \n                  - Skip to the next iteration\n                  '

In [ ]:
#for loop
fruits = ["apple","banana","mango"]
for fruit in fruits:
  print(fruit)
#while loop
count = 0
while count < 5:
  print("Count is: ", count)
  count +=1
#Break
fruits = ["apple","banana","mango"]
print("loop 1")
for fruit in fruits:
  print(fruit)
  if fruit == "apple":
    break
#continue
print("loop 2")
for fruit in fruits:
  if fruit == "apple":
    continue
  else:
    print(fruit)


apple
banana
mango
Count is:  0
Count is:  1
Count is:  2
Count is:  3
Count is:  4
loop 1
apple
loop 2
banana
mango


4. Functions

In [ ]:
# Function Name
    # - identifier by which the function is called

 # Input Parameters
    # - variables listed within the parantheses.
    # - Parameters allow function to accept inputs, which are used within the function's body to perform operations
    # - flexible and reusable, as they allow pass different values each time when function called.

# Return Output
    # - specifies the output of the function
    # - allowing it to send back a result to the part of the program where it was called
    # - It enables further processing or storage of the function's output.
    # - if no return statement is specified, the function return - None by default

4.1 Buit-In Function

In [ ]:
print("Hello, World!")
length = len("Hello")
data_type = type(42) #Output: <class 'int'>
total = sum([5,4,3])

Hello, World!


In [ ]:
#str.upper(): converts all characters in a string to uppercase
msg = "hello".upper() #output: "HELLO"
#list.append(): adds an element to the end of a list.
fruits = ["apple", "mango"]
fruits.append("banana") #output: ["apple","mango","banana"]
#dict.get(): returns the value associated with a key in a dictionary
info = {"name": "Alice", "age": 25}
age = info.get("age") #output: 25

4.2 User-Defined Fucntion

##### def temperature_converter():        
        print("Choose conversion type:")
        print("1. Celsius to Fahrenheit")
        print("2. Fahrenheit to Celsius")
#### Get conversion choice from user
        choice = input("Enter 1 or 2: ")
        if choice == "1":
            # Celsius to Fahrenheit conversion
            celsius = float(input("Enter temperature in Celsius: "))
            fahrenheit = (celsius * 9/5) + 32
            print(f"{celsius}C is equal to {fahrenheit}F")
            return fahrenheit
        elif choice == "2":
            # Fahrenheit to Celsius conversion
            fahrenheit = float(input("Enter temperature in Fahrenheit: "))
            celsius = (fahrenheit - 32) * 5/9
            print(f"{fahrenheit}F is equal to {celsius}C")
            return celsius
        else:
            print("Invalid choice. Please enter 1 or 2.")
            return None
#### Call the function
temperature_converter()

5. Global or Local Variable


5.1 Global Variable

In [ ]:
x = 20 #Global variable.
def print_global():
  print(x) #accessing global variable
print_global() #output: 20

20


5.2 Local Variable

In [ ]:
def print_local():
  y = 2 #local variable
  print(y)

print_local() #output: 2
#print(y) #this would cause an error because y is not accessible outside the function

2


5.3 Accessing and Modifying Global Variables Inside a fucntion

In [ ]:
x = 10 #global variable
def modify_global():
  global x #declaring x as a global
  x = 20 #modifying global x
modify_global()
print(x) #output: 20

20


6. Exception and Error Handling

1. #### Types of error
    -  ##### Syntax Error
        - print("Hello World)  # Missing closing quote
    - ##### Exceptions
        - result = 10 / 0  # Raises ZeroDivisionError

2. #### Handling Exception
    - Try, except, Finally
    - Finally block is optional and executes regardless of whether an exception occurs or not.

3. #### Raising Custom Exception
    - Python allows the creation of custom exceptions using the raise statement.
    - Usefulf or handling specific erroes not covered by built-in exceptions.
    - def check_age(age):
             if age < 0:
                 raise ValueError("Age cannot be negative.")
             else:
                 print("Valid age")
         try:
             check_age(-1)
         except ValueError as e:
             print(e)
    - it raises a ValueError if an invalid age is provided

7. TO DO Task

7.1 Exercise on Functions

Task-1

In [ ]:
"""
Create a Python program that converts between different units of measurement.

• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.

• Requirements:

1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and return value.

• Conversion Options:
1. Length:
   – Convert meters (m) to feet (ft).
   – Convert feet (ft) to meters (m).
2. Weight:
    – Convert kilograms (kg) to pounds (lbs).
    – Convert pounds (lbs) to kilograms (kg).
3. Volume:
   – Convert liters (L) to gallons (gal).
   – Convert gallons (gal) to liters (L).

"""
def conversion():
  """
    Conversion function performs unit conversions for length, weight, and volume.

    • Conversion Options:
        Length: – Convert meters (m) to feet (ft).
                – Convert feet (ft) to meters (m).
        Weight: – Convert kilograms (kg) to pounds (lbs).
                – Convert pounds (lbs) to kilograms (kg).
        Volume: – Convert liters (L) to gallons (gal).
                – Convert gallons (gal) to liters (L).
    """
  while True:
      print("Choose conversion options: \n 1. Length \n 2. Weight \n 3. Volume")
      choice = input("Enter 1-3: ")

      if choice in ["1","2","3"]:
        break
      else:
        print("Invalid choice. Please enter valid number between 1 to 3.")

  try:
      if choice == "1":
        print("Length Conversion")
        print("1. Convert meters(m) to feet(ft). \n 2. convert feet(ft) to meters(m).")
        while True:
          lengthChoice = input ("Enter 1 or 2: ")
          if lengthChoice in ["1","2"]:
            if lengthChoice == "1":
              meter = float(input("Enter length in meters(m): "))
              feet = meter*3.28084
              print (f"{meter} m is equal to {feet:4f} ft.")
            else:
              feet = float(input("Enter length in feet(ft): "))
              meter = feet / 3.28084
              print(f"{feet} ft is eual to {meter:4f} m.")
            break
          else:
            print("Invalid input. Please enter 1 or 2.")

      elif choice == "2":
        print("Weight Conversion")
        print("1. convert kilograms(kg) to pounds(lbs). \n 2. convert pounds(lbs) to kilograms(kg).")
        while True:
          weightChoice = input("Enter 1 or 2: ")
          if weightChoice in ["1", "2"]:
            if weightChoice == "1":
              kilogram = float(input("Enter weight in kilograms(kg): "))
              pound = kilogram * 2.20462
              print(f"{kilogram} kg is equal to {pound:.4f} lbs.")
            else:
              pound = float(input("Enter weight in pounds(lbs): "))
              kilogram = pound/2.20462
              print(f"{pound} lbs is equal to {kilogram:.4f} kg.")
            break
          else:
            print("Invalid input! Please enter 1 or 2.")

      elif choice == "3":
        print("Volume Conversion")
        print("1. convert liters(L) to gallons(gal). \n 2. convert gallons(gal) to liters(L).")
        while True:
          volumeChoice = input("Enter 1 or 2: ")
          if volumeChoice in ["1", "2"]:
            if volumeChoice == "1":
              liters = float(input("Enter volume in liters(L): "))
              gallons = liters * 0.264172
              print(f"{liters} L is equal to {gallons:.4f} gal.")
            else:
              gallons = float(input("Enter volume in gallons(gal): "))
              liters = gallons/0.264172
              print(f"{gallons} gal is equal to {liters:.4f} L.")
            break
          else:
            print("Invalid input! Please enter 1 or 2.")


  except ValueError:
      print("Invalid input! Please enter a valid input.")

conversion()


Choose conversion options: 
 1. Length 
 2. Weight 
 3. Volume
Enter 1-3: 2
Weight Conversion
1. convert kilograms(kg) to pounds(lbs). 
 2. convert pounds(lbs) to kilograms(kg).
Enter 1 or 2: 1
Enter weight in kilograms(kg): 50
50.0 kg is equal to 110.2310 lbs.


Task 02

In [ ]:
"""
Create a Python program that performs various mathematical operations on a list of numbers.

• The Program should:
    1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
    of the numbers).
    2. Ask the user to input a list of numbers (separated by spaces).
    3. Perform the selected operation and display the result.
    4. Handle potential errors, such as invalid input or empty lists.

• Requirements:
    1. Functions: Define at least one function for each operation (sum, average, maximum, minimum).
    2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or empty lists).
    3. User Input: Prompt the user to select the operation and input the list of numbers.
    4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
    return value.
"""
def calculate_sum(numbers):
  """
    Calculates the sum of a list of numbers using for loop.
    numbers list is passed as a parameter.
    The sum value is returned.
    """
  total = 0
  for num in numbers:
       total += num
  return total

def calculate_average(numbers):
   """
    Calculates the average of a list of numbers making use of calculate_sum user defined function .
    List of numbers is passed.
    Average value is returned
     """
   total = calculate_sum(numbers)
   return total/len(numbers)

def find_maximum(numbers):
   """
    Finds the maximum value in a list of numbers.
    Numbers list is passed.
    Maximum value is returned.
    """
   if not numbers:
    return None
   max_value = numbers[0]
   for num in numbers:
    if num>max_value:
        max_value = num
   return max_value

def find_minimum(numbers):
   """
    Finds the minimum value in a list of numbers.
    List of numbers is passed
    Minimum value is returned.
    """
   if not numbers:
    return None
   min_value = numbers[0]
   for num in numbers:
    if num<min_value:
      min_value = num
   return min_value

print("Mathematical Operations on a list of numbers")
print("1. Sum")
print("2. Average")
print("3. Maximum")
print("4. Minimum")

try:
  choice = int(input("Choose an operation (1-4)"))
  numbers = input("Enter numbers seperated by spaces: ").split()
  numbers = [float(num) for num in numbers]

  if not numbers:
    raise ValueError("List cannot be empty.")

  if choice ==1:
    result = calculate_sum(numbers)
    print(f"The sum of numbers in the list is: {result:.2f}")
  elif choice==2:
    result = calculate_average(numbers)
    print(f"The average of numbers in the list is: {result:.2f}")
  elif choice==3:
    result = find_maximum(numbers)
    print(f"The maximum number in the list is: {result:.2f}")
  elif choice==4:
    result = find_minimum(numbers)
    print(f"The minimum number in the list is: {result:.2f}")
  else:
    print("Invalid choice.")

except ValueError as e:
  print(f"Error: {e}")
except Exception:
  print("An unexpected error occured.")

Mathematical Operations on a list of numbers
1. Sum
2. Average
3. Maximum
4. Minimum
Choose an operation (1-4)1
Enter numbers seperated by spaces: 1 2 3 4 5
The sum of numbers in the list is: 15.00


List Manipulation

Task 1

In [ ]:
#Extract every other element

def extract_num(num_list):
   """
    Extract every other number from a list of numbers.
    Number list is provided a parameter.
    New list with every other item of the list from first is displayed

    """
   return num_list[::2]

sample_list = [1,2,3,4,5,6]
new_list = extract_num(sample_list)

print("The new list is: ", new_list)

The new list is:  [1, 3, 5]


Task 2

In [ ]:
#Slice a sublist

def get_sublist(lst, start, end):
  new_list = []
  for i in range(start, end+1):
    if 0 <= i < len(lst):
      new_list.append(lst[i])
  return new_list

list = [1,2,3,4,5,6]
start = int(input("Enter the start index: "))
end = int(input("Enter the end index: "))

new_list = get_sublist(list, start, end)
print("The new list is: ", new_list)

Enter the start index: 1
Enter the end index: 5
The new list is:  [2, 3, 4, 5, 6]


Task 3

In [ ]:
#Reverse a list using slicing:

def list_reverse(lst):
  return lst[::-1]

list = [1,2,3,4,5,6]
reverse_list = list_reverse(list)

print("Original list: ", list)
print("The reversed list is: ", reverse_list)

Original list:  [1, 2, 3, 4, 5, 6]
The reversed list is:  [6, 5, 4, 3, 2, 1]


Task 4

In [ ]:
#remove the first and last elements:

def remove(lst):
  return lst[1:-1]

list = [1,2,3,4,5,6]
result = remove(list)

print("The new list is: ", result)

The new list is:  [2, 3, 4, 5]


Task 5

In [ ]:
#Get the first n element

def get_first_n(lst,n):
  return lst[:n]

num = int(input("Enter the numer of elements: "))
list = [1,2,3,4,5,6]

print("Result: ", get_first_n(list,num))

Enter the numer of elements: 3
Result:  [1, 2, 3]


Task 6

In [ ]:
#Extract element from the end

def get_last_n(lst,n):
  return lst[-n:]

num = int(input("Enter the number of elements:"))
list = [1,2,3,4,5,6]

print("Result: ", get_last_n(list, num))

Enter the number of elements:2
Result:  [5, 6]


Task 7

In [ ]:
#Extract elements in reverse order

def reverse_skip(lst):
  return lst[-2::-2]

list = [1,2,3,4,5,6]
print("Result: ", reverse_skip(list))

Result:  [5, 3, 1]


8. Exercise on Nested Lists

Task 1

In [ ]:
#flatten a nested list

def flatten(lst):
  flat_list = []
  for i in lst:
    for j in i:
      flat_list.append(j)
  return flat_list

nested_list = [[1,2],[3,4],[5,6]]
print("Flatten list: ", flatten(nested_list))

Flatten list:  [1, 2, 3, 4, 5, 6]


Task 2

In [ ]:
#Accessing nested list elements

def access_nested_element(lst, indicies):
  element = lst
  for index in indicies:
    element = element[index]

  return element

list = [[1,2,3],[4,5,6],[7,8,9]]
indicies = [1,0]

print("Result: ", access_nested_element(list,indicies))

Result:  4


Task 3

In [ ]:
def sum_nested(lst):
  sum = 0
  for num in lst:
    if isinstance(num,list):
      sum += sum_nested(num)

    elif isinstance(num, (int,float)):
      sum += num
  return sum

S_list = [[1,2],[3,[4,5]],6]
result = sum_nested(S_list)
print("The sum of elements is: ", result)

TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union

Task 4

In [ ]:
#Remove specific element from a nested list
def remove_element(lst, elm):
    new_lst=[]
    for num in lst:
        if isinstance(num, list):
            sub_list = remove_element(num, elm)
            if sub_list:
                new_lst.append(sub_list)
        elif num != elm:
            new_lst.append(num)
    return new_lst

sample_list =  [[1, 2], [3, 2], [4, 5]]
element = 2
print("New List:", remove_element(sample_list, element))

TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union

Task 5

In [ ]:
#find the maximum element in an nested list

def find_max(lst):
  max_num = 0
  for num in lst:
    if isinstance(num,list):
      max_num = max(max_num,find_max(num))
    else: max_num = max(max_num, num)
  return max_num

sample_list = [[1,2],[3,[4,7]],6]
print("The maximum number in the list is: ", find_max(sample_list))

TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union

Task 6

In [ ]:
#Count occurences of an element in a nested list

def count(lst,element):
  n = 0
  for num in lst:
    if isinstance(num,list):
      n += count(num, element)
    elif num == element:
      n += 1
  return n

sample_list = [[1,2],[2,3],[2,4]]
element = 2
print(f"The number of {element} in the list is: ", count(sample_list,element))

TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union

Task 7

In [ ]:
#Flatten a list of lists of lists

def flatten(lst):
  new_list = []
  for item in lst:
    if isinstance(item,list):
      new_list.extend(flatten(item))
    else:
      new_list.append(item)
  return new_list

sample_list = [[[1,2],[3,4]],[[5,6],[7,8]]]
print("New flattened list is: ", flatten(sample_list))

TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union

Task 8

In [ ]:
#Nested list average

def average_nested(lst):
  def helper(current_list):
    total = 0.0
    count = 0
    for element in current_list:
      if isinstance(element, list):
        sub_total, sub_count = helper(element)
        total += sub_total
        count += sub_count
      elif isinstance(element, (int,float)) and not isinstance(element,bool):
        total += element
        count += 1
    return total, count

  total_sum, total_count = helper(lst)
  return total_sum/total_count if total_count != 0 else 0.0

sample_list = [[1,2],[3,4],[5,6]]
print("The average is: ", average_nested(sample_list))




TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union

9. Numpy

Problem - 1: Array Creation

In [ ]:
import numpy as np


Task 1

In [ ]:
# Initialize an empty array with size 2 x 2

array = np.zeros((2,2))
print("Empty array", array)

Empty array [[0. 0.]
 [0. 0.]]


Task 2

In [ ]:
#Initialize an all one array with size 4x2

array = np.ones((4,2))
print("One array", array)

One array [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


Task 3

In [ ]:
#Return a new array of given shape and type, filled with value

rows = int(input("Enter the number of rows: "))
cols = int(input("Enter the number of columns: "))
shape = (rows,cols)

fill_value = float(input("Enter the fill values: "))
dtype_input = input("Enter the data type (int, float, str): ").strip().lower()

dtype_mapping = {
    "int": np.int32,
    "float": np.float32,
    "str": str

}
dtype = dtype_mapping.get(dtype_input, np.float32)

array = np.full(shape, fill_value, dtype=dtype)
print("\n Generated Arraya:\n", array)

Enter the number of rows: 4
Enter the number of columns: 3
Enter the fill values: 5
Enter the data type (int, float, str): int

 Generated Arraya:
 [[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


Task 4

In [ ]:
rows = int(input("Enter the number of rows: "))
cols = int(input("Enter the number of columns: "))
shape = (rows,cols)

dtype_input = input("Enter the data type (int,float): ").strip().lower()
dtype_mapping = {"int": np.int32, "float": np.float32}
dtype = dtype_mapping.get(dtype_input, np.float32)

fill_value = float(input("Enter a fill value for the original array: "))
original_array = np.full(shape, fill_value, dtype = dtype)

zeros_array = np.zeros_like(original_array)

print("\n Original Array: \n", original_array)
print("\n New Array of zeros: \n", zeros_array)

Enter the number of rows: 4
Enter the number of columns: 5
Enter the data type (int,float): int
Enter a fill value for the original array: 6

 Original Array: 
 [[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]

 New Array of zeros: 
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


Task 5

In [ ]:
rows = int(input("Enter the number of rows: "))
cols = int(input("Enter the number of columns: "))
shape = (rows,cols)

dtype_input = input("Enter the data type (int,float): ").strip().lower()
dtype_mapping = {"int": np.int32, "float": np.float32}
dtype = dtype_mapping.get(dtype_input, np.float32)

fill_value = float(input("Enter a fill value for the original array: "))
original_array = np.full(shape, fill_value, dtype = dtype)

ones_array = np.ones_like(original_array)

print("\n Original Array: \n", original_array)
print("\n New Array of zeros: \n", ones_array)

Enter the number of rows: 4
Enter the number of columns: 5
Enter the data type (int,float): int
Enter a fill value for the original array: 9

 Original Array: 
 [[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]

 New Array of zeros: 
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


Task 6

In [ ]:
input_list = input("Enter numbers seperated by space: ")
new_list = list(map(int, input_list.split()))
np_array = np.array(new_list)

print("\nOriginal List: ", new_list)
print("Numpy Array: ", np_array)

Enter numbers seperated by space: 1 2 3 4 5


TypeError: 'list' object is not callable

Problem - 2: Array Manipulation: Numerical Ranges and Array Indexing

Task 1

In [ ]:
#Create an array with values ranging from 10 to 49

array = np.arange(10,50)
print("Array with value from 10-49: ", array)

Array with value from 10-49:  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Task 2

In [ ]:
#Create a 3x3 matrix with values ranging from 0 to 8

array = np.arange(9).reshape(3,3)
print("Matrix with values ranging from 0-8: \n", array)

Matrix with values ranging from 0-8: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


Task 3

In [ ]:
#Create a 3x3 identity matrix.
array = np.eye(3)
print("\n 3x3 identity matrix: \n", array)


 3x3 identity matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Task 4

In [ ]:
#Create a random array of size 30 and fill the mean of the array

array = np.random.random(30)
meanValue = array.mean()
print("\n Random array of size 30:\n", array)
print("Mean of the array: ", meanValue)


 Random array of size 30:
 [0.61121037 0.07536464 0.14828426 0.53996755 0.66948935 0.34123752
 0.20607708 0.66368393 0.78389304 0.24103071 0.99749275 0.14912039
 0.80289987 0.70554594 0.53718117 0.2776688  0.2995815  0.33994905
 0.11650299 0.86861296 0.07878641 0.15135754 0.74839696 0.16380409
 0.85547214 0.34918876 0.27990719 0.0745553  0.888491   0.23962229]
Mean of the array:  0.4401458515400229


Task 5

In [ ]:
#Create a 10x10 array with random values and find max and min values

array = np.random.random((10,10))
minValue = array.min()
maxValue = array.max()

print("\n 10x10 Random array: \n", array)
print("Minimum value: ", minValue)
print("Maximum value: ",maxValue)


 10x10 Random array: 
 [[0.56662418 0.31386194 0.57830052 0.73242987 0.1750247  0.37587508
  0.20653053 0.16885389 0.04635737 0.85991434]
 [0.5111323  0.93302863 0.73921187 0.7177675  0.72305297 0.56672803
  0.08659365 0.14345977 0.26973923 0.75340682]
 [0.07406207 0.75980784 0.73537723 0.16046255 0.60514497 0.32503493
  0.61758113 0.80479645 0.66663231 0.29954948]
 [0.42469996 0.67013839 0.41951433 0.11093268 0.92926915 0.58436921
  0.55535388 0.02768228 0.32745809 0.73405025]
 [0.94640974 0.53936801 0.17971363 0.05552504 0.78774155 0.42047099
  0.74146596 0.01898749 0.19104264 0.02262911]
 [0.5253095  0.82678427 0.79415549 0.72437924 0.6935638  0.12136718
  0.70840774 0.57496355 0.59484877 0.58338153]
 [0.58256868 0.17275774 0.87774978 0.5697964  0.28431044 0.87130265
  0.02566956 0.663629   0.1177117  0.68959658]
 [0.54403256 0.35479438 0.52672793 0.64404927 0.19354018 0.7814849
  0.83352799 0.18501614 0.85703559 0.4453585 ]
 [0.51470656 0.20942784 0.10274637 0.33727621 0.78908004 

Task 6

In [ ]:
#Create a zero array of size 10 and replace the 5th element with 1

array = np.zeros(10)
array[4] = 1
print("\n Zero array with 5th element replaced by 1: ", array)


 Zero array with 5th element replaced by 1:  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Task 7

In [ ]:
#Reverse an array

array = np.array([1,2,3,4,5])
reversedArray = array[::-1]
print("\n Reversed array: ", reversedArray)


 Reversed array:  [5 4 3 2 1]


Task 8

In [ ]:
# Create a 2D array with 1 on the border and 0 inside

array = np.ones((5,5))
array[1:-1,1:-1] = 0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Task 9

In [ ]:
#Create an 8x8 matrix and fill it with a checkboard pattern

array = np.zeros((8,8))
array[1::2, ::2] = 1
array[::2, 1::2] = 1
print(array)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Problem-3: Array Operation

Task 1

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

#Add two array
sum_1 = x+y
print("The sum of x and y is: ", sum_1)

#Add v and w
sum_2 = v+w
print("The sum of v and w is: ", sum_2)

The sum of x and y is:  [[ 6  8]
 [10 13]]
The sum of v and w is:  [20 22]


Task 2

In [ ]:
#Substracting the two array
sub_1 = x-y
print("The difference of x and y is: ", sub_1)

sub_2 = v-w
print("The difference of v and w is: ", sub_2)

The difference of x and y is:  [[-4 -4]
 [-4 -3]]
The difference of v and w is:  [-2 -2]


Task 3

In [ ]:
# Multiply the array with any integers

num = int(input("Enter a number: "))

mul_x = x*num
print("Multiplication of array x: ", mul_x)

mul_y = y*num
print("Multiplication of array y: ", mul_y)

mul_v = v*num
print("Multiplication of array v: ", mul_v)

mul_w = w*num
print("Multiplication of array w: ", mul_w)

Enter a number: 3
Multiplication of array x:  [[ 3  6]
 [ 9 15]]
Multiplication of array y:  [[15 18]
 [21 24]]
Multiplication of array v:  [27 30]
Multiplication of array w:  [33 36]


Task 4

In [ ]:
#Find the square of each element of the array

sq_x = x**2
print("Square of array x: ", sq_x )

sq_y = y**2
print("Square of array y: ", sq_y )

sq_v = v**2
print("Square of array v: ", sq_v )

sq_w = w**2
print("Square of array w: ", sq_w )

Square of array x:  [[ 1  4]
 [ 9 25]]
Square of array y:  [[25 36]
 [49 64]]
Square of array v:  [ 81 100]
Square of array w:  [121 144]


Task 5

In [ ]:
#Find the dot product between: v and w, x and v, and y

dot_vw = np.dot(v,w)
print("Dot product of v and w is: ", dot_vw)

dot_xv = np.dot(x,v)
print("Dot product of x and v is: ", dot_xv)

dot_xy = np.dot(x,y)
print("Dot product of x and y is: ", dot_xy)


Dot product of v and w is:  219
Dot product of x and v is:  [29 77]
Dot product of x and y is:  [[19 22]
 [50 58]]


Task 6

In [ ]:
#Concatenate a and y along row and concatenate v and w along column

concatenate_xy = np.concatenate((x,y), axis = 0)
print(concatenate_xy)

concatenate_vw = np.vstack((v,w))
print(concatenate_vw)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


Task 7

In [ ]:
#concatenate x and v, if you get an error, observe and explain why did you get error

try:
  np.concatenate((x,v))
except ValueError as e:
  error_msg = e
  print("Error Concating x and v:", error_msg)


Error Concating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem-4: Matrix Operations

Task 1

In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

In [ ]:
# A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]])
# 1. Prove A.A−1 = I

A_Inverse = np.linalg.inv(A)
I = np.eye(2)
result = np.dot(A,A_Inverse)
print("A.A-1: ",result)

print("\n Is A*A_Inverse an identity matrix? ", np.allclose(result,I))

A.A-1:  [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

 Is A*A_Inverse an identity matrix?  True


Task 2

In [ ]:
# Prove AB not equal to BA

AB = np.dot(A,B)
BA = np.dot(B,A)
print("\n Ab = \n", AB, "\n")
print("BA = \n", BA, "\n")

print("Is AB equal to BA? ", np.array_equal(AB,BA))


 Ab = 
 [[23 13]
 [51 29]] 

BA = 
 [[36 44]
 [13 16]] 

Is AB equal to BA?  False


Task 3

In [ ]:
# Prove (AB)^T = B^T * A^T
AB_T = np.transpose(AB)
BT_AT = np.dot(np.transpose(B),np.transpose(A))
print("\n (AB)^T =\n", AB_T, "\n")
print("B^T * A^T =\n", BT_AT, "\n ")
print("(AB)^T = B^T * A^T ? ", np.array_equal(AB_T, BT_AT))


 (AB)^T =
 [[23 51]
 [13 29]] 

B^T * A^T =
 [[23 51]
 [13 29]] 
 
(AB)^T = B^T * A^T ?  True


Task 4
Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

•Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [ ]:
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9

A_eq = np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
B_eq = np.array([-1,-3,9])

A_eq_inv = np.linalg.inv(A_eq)
result = np.dot(A_eq_inv, B_eq)

print("Solution the system of equation is: ", result)

Solution the system of equation is:  [ 2.  1. -2.]


Experiment

 Element wise Addition

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

import time

def list_addition(list1, list2):
    result = []
    for i in range(len(list1)):
        result.append(list1[i]+list2[i])
    return result

def array_addition(arr1, arr2):
    return arr1 + arr2
    
size = 1000000

list1 = list(range(size))
list2 = list(range(size))
list_start_time = time.time()
list_result = list_addition(list1, list2)
list_end_time = time.time()
list_time = list_end_time-list_start_time

array1 = np.arange(size)
array2 = np.arange(size)
arr_start_time = time.time()
arr_result = array_addition(array1, array2)
arr_end_time = time.time()
arr_time = arr_end_time - arr_start_time

print(f"Time taken by list: {list_time:.6f} seconds")
print(f"Time taken by array: {arr_time:.6f} seconds")

Element wise Multiplication
• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [ ]:
import time
def list_multiplication(list1, list2):
  result = []
  for i in range (len(list1)):
    result.append(list1[i]*list2[i])
  return result

def array_multiplication(arr1, arr2):
  return arr1*arr2

size = 1000000

list1 = list(range(size))
list2 = list(range(size))
list_start_time = time.time()
list_result = list_multiplication(list1, list2)
list_end_time = time.time()
list_time = list_end_time - list_start_time

array1 = np.arrange(size)
array2 = np.arrange(size)
arr_start_time = time.time()
arr_result = array_multiplication(array1, array2)
arr_end_time = time.time()
arr_time = arr_end_time - arr_start_time

print(f"Time taken by list: {list_time:'6f'} seconds")
print(f"Time taken by array: {arr_time:.6f} seconds")

TypeError: 'list' object is not callable

Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [ ]:
def list_dotproduct(list1, list2):
  dp_list = 0
  for i in range (len(list1)):
    dp_list += list1[i]*list2[i]
  return dp_list

def array_dotproduct(arr1, arr2):
  return np.dot(arr1, arr2)

size = 1000000

list1 = list(range(size))
list2 = list(range(size))
list_start_time = time.time()
list_result = list_dotproduct(list1, list2)
list_end_time = time.time()
list_time = list_end_time - list_start_time

array1 = np.arrange(size)
array2 = np.arrange(size)
arr_start_time = time.time()
arr_result = array_dotproduct(array1, array2)
arr_end_time = time.time()
arr_time = arr_end_time - arr_start_time

print(f"Time taken by list: {list_time:'6f'} seconds")
print(f"Time taken by array: {arr_time:.6f} seconds")

TypeError: 'list' object is not callable

Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [ ]:
import random
def list_matrix_mul(mat1, mat2):
  result = [[0 for _ in range(size)] for _ in range(size)]
  for i in range(size):
    for j in range(size):
      for k in range(size):
        result[i][j] += mat1[i][k] * mat2[k][j]

  return result

def numpy_matrix_mul(mat1, mat2):
  return np.matmul(mat1, mat2)

size = 1000

matrix1 = [[random.randint(1,100) for _ in range(size)] for _ in range(size)]
matrix2 = [[random.randint(1,100) for _ in range(size)] for _ in range(size)]

list_start_time = time.time()
list_mul = list_matrix_mul(matrix1, matrix2)
list_end_time = time.time()
list_time = list_end_time - list_start_time

numpy_start_time = time.time()
np_mul = numpy_matrix_mul(matrix1, matrix2)
numpy_end_time = time.time()
np_time = numpy_end_time - numpy_start_time

print(f"Time for list matrix multiplication is: {list_time:.6f} seconds")
print(f"Time for numpy matrix multiplication is: {np_time:.6f} seconds")

Time for list matrix multiplication is: 103.246186 seconds
Time for numpy matrix multiplication is: 1.029102 seconds
